name: travel_app_ui


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/icons/category/
    - assets/icons/contacts/
    - assets/icons/places/
    - assets/icons/popular/
    - assets/icons/
    - assets/


  uses-material-design: true


